version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 5

    - package-ecosystem: 'npm'
      directory: '/generators/client/templates/svelte/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 5
      versioning-strategy: increase
