version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10

    - package-ecosystem: 'npm'
      directory: '/generators/client/templates/svelte/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      versioning-strategy: increase

    - package-ecosystem: 'npm'
      directory: '/generators/client/templates/svelte/swagger/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      versioning-strategy: increase

    - package-ecosystem: 'npm'
      directory: '/generators/client/templates/svelte/java-prettier/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      versioning-strategy: increase
