name: Svelte Application Generator
on: [push, pull_request]
env:
    TEST_SCRIPTS_PATH: ${{ github.workspace }}/.github/workflows/scripts
jobs:
    generator-jhipster-svelte:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                apps: ['monolithic-session.json']
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Download latest chrome binary
              run: |
                  sudo apt-get update
                  sudo apt-get install google-chrome-stable -y
                  sudo apt-get install xvfb
            - name: Create Svelte Hipster docker image
              run: |
                  docker build -t jhipster/svelte-hipster:latest .
            - name: Generate application
              run: |
                  mkdir -p "$HOME/svelte-app"
                  cd "$HOME/svelte-app"
                  cp $TEST_SCRIPTS_PATH/${{ matrix.apps }} .yo-rc.json
                  docker run --rm -v $PWD:/app --user $(id -u) --env UID=$(id -u) --env GID=$(id -g) jhipster/svelte-hipster --no-insight
