name: Svelte Lighthouse Applications
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
env:
    TEST_SCRIPTS_PATH: ${{ github.workspace }}/.github/workflows/scripts
jobs:
    build:
        name: ${{ matrix.apps }}
        concurrency:
            group: lighthouse-${{ github.head_ref }}-${{ matrix.apps }}
            cancel-in-progress: true
        runs-on: ${{ matrix.os }}
        timeout-minutes: 20
        strategy:
            fail-fast: false
            matrix:
                apps: ['svelte-app-session-lighthouse.jdl']
                os: [ubuntu-latest]
                node_version: [14.x]
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Download latest chrome binary
              if: contains(matrix.os , 'ubuntu-latest')
              run: |
                  sudo apt-get update
                  sudo apt-get install google-chrome-stable -y
                  sudo apt-get install xvfb
            - uses: actions/setup-java@v1
              with:
                  java-version: '11'
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Maven - Configure cache
              uses: actions/cache@v2
              if: contains(matrix.apps, 'maven')
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-7.1.0
            - name: Configure cypress cache
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.cache/Cypress/8.1.0
                      ~/.cache/Cypress/cy
                  key: ${{ runner.os }}-cypress-8.1.0
            - name: Create Svelte Hipster docker image
              run: |
                  docker build -t jhipster/svelte-hipster:latest --build-arg UID=$(id -u) --build-arg GID=$(id -g) .
            - name: Prepare environment
              run: |
                  mkdir -p "$HOME/svelte-app"
                  mkdir -p "$HOME/.m2"
                  mkdir -p "$HOME/.gradle"
                  mkdir -p "$HOME/.cache"
            - name: Generate application
              run: |
                  cd "$HOME/svelte-app"
                  cp $TEST_SCRIPTS_PATH/${{ matrix.apps }} app.jdl
                  docker run --rm -v $PWD:/app -v $HOME/.cache:/home/shipster/.cache  jhipster/svelte-hipster import-jdl app.jdl --no-insight --force
                  rm -rf node_modules/generator-jhipster-svelte
            - name: Build application docker image
              run: |
                  cd "$HOME/svelte-app"
                  ./mvnw -ntp -Pprod compile jib:dockerBuild
            - name: Prepare Lighthouse run prerequisites
              run: |
                  cd "$HOME/svelte-app"
                  npm install -g @lhci/cli@0.7.x
                  npm install --save puppeteer
                  docker-compose -f src/main/docker/app.yml up -d
                  timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/api/authenticate)" != "200" ]]; do sleep 5; done' || false
            - name: Run Lighthouse tests - Unauthenticated Pages
              run: |
                  cd "$HOME/svelte-app"
                  cp $TEST_SCRIPTS_PATH/lighthouse/lighthouserc.json lighthouserc.json
                  lhci autorun
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
            - name: Run Lighthouse tests - Authenticated Pages
              run: |
                  cd "$HOME/svelte-app"
                  cp $TEST_SCRIPTS_PATH/lighthouse/lighthouserc-auth.json lighthouserc.json
                  cp $TEST_SCRIPTS_PATH/lighthouse/puppeteer-auth.cjs puppeteer-auth.cjs
                  lhci autorun
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
