name: Svelte Generator
on: [push, pull_request]
jobs:
    generator-jhipster-svelte:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 20
        strategy:
            fail-fast: false
            matrix:
                node_version: [12.x]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - run: npm run lint
