name: Svelte Generator
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    generator-jhipster-svelte:
        concurrency:
            group: generator-${{ matrix.node_version }}-${{ matrix.apps }}-${{ github.head_ref || github.sha }}
            cancel-in-progress: true
        runs-on: ${{ matrix.os }}
        timeout-minutes: 20
        strategy:
            fail-fast: false
            matrix:
                node_version: [12.x, 14.x]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - run: npm ci
            - run: npm run lint
    publish-docker-image:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
        steps:
            - name: Checkout svelte generator repository
              uses: actions/checkout@v2
            - uses: docker/metadata-action@v3
              with:
                  images: jhipster/svelte-hipster
                  tags: |
                      type=ref,event=branch
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push Svelte Hipster main branch image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
